-- CEMENT LOADING DASHBOARD
-- Shared history for GitHub Pages / any TV / any computer
--
-- Run this once in Supabase SQL Editor.
--
-- This table stores complete dashboard snapshots.
-- Automatic cleanup keeps only the last 7 days.

create table if not exists public.dashboard_history (
  id bigint generated by default as identity primary key,
  recorded_at timestamptz not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists dashboard_history_recorded_at_idx
  on public.dashboard_history (recorded_at desc);

alter table public.dashboard_history enable row level security;

-- Public dashboard can read history.
drop policy if exists "dashboard history read" on public.dashboard_history;
create policy "dashboard history read"
on public.dashboard_history
for select
to anon
using (true);

-- Public dashboard can insert snapshots.
drop policy if exists "dashboard history insert" on public.dashboard_history;
create policy "dashboard history insert"
on public.dashboard_history
for insert
to anon
with check (true);

-- Public dashboard can delete only records older than 7 days.
-- The browser cleanup is also performed by app.js.
drop policy if exists "dashboard history cleanup" on public.dashboard_history;
create policy "dashboard history cleanup"
on public.dashboard_history
for delete
to anon
using (
  recorded_at < now() - interval '7 days'
);

-- Optional database-side cleanup function.
-- Run it manually if desired:
create or replace function public.cleanup_dashboard_history()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.dashboard_history
  where recorded_at < now() - interval '7 days';
$$;
